In [1]:
import pandas as pd
import xlwt
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# 获取源数据
data = pd.read_excel('data/corona_virus.xls',index_col=0)


In [2]:
#查看有无缺失值
print(data.info(), '\n')

<class 'pandas.core.frame.DataFrame'>
Index: 214 entries, 法国 to 南非
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   confirmedCount         214 non-null    int64  
 1   currentConfirmedCount  214 non-null    int64  
 2   curedCount             214 non-null    int64  
 3   deadCount              214 non-null    int64  
 4   deadRate               214 non-null    float64
 5   deadRateRank           214 non-null    int64  
 6   confirmedCountRank     214 non-null    int64  
 7   deadCountRank          214 non-null    int64  
dtypes: float64(1), int64(7)
memory usage: 15.0+ KB
None 



In [3]:
#查看数据特征
print(data.describe())

       confirmedCount  currentConfirmedCount    curedCount     deadCount  \
count    2.140000e+02           2.140000e+02  2.140000e+02  2.140000e+02   
mean     3.021510e+06           1.156810e+06  1.984045e+06  3.123777e+04   
std      9.437636e+06           4.408084e+06  8.313567e+06  1.062549e+05   
min      1.770000e+02           0.000000e+00  0.000000e+00  0.000000e+00   
25%      3.844775e+04           5.400500e+03  1.126825e+04  3.000000e+02   
50%      2.585425e+05           3.756500e+04  1.317610e+05  2.790000e+03   
75%      1.375864e+06           2.979212e+05  6.079252e+05  1.667500e+04   
max      1.009061e+08           3.748769e+07  9.832055e+07  1.106990e+06   

         deadRate  deadRateRank  confirmedCountRank  deadCountRank  
count  214.000000    214.000000          214.000000     214.000000  
mean     1.338832    107.070093          107.500000     107.453271  
std      1.603597     61.786090           61.920648      61.876791  
min      0.000000      1.000000        

In [4]:
#归一化处理
normalization_data=MinMaxScaler().fit_transform(data)
normalization_data=[[round(j,2) for j in normalization_data[i]] for i in range(len(normalization_data))]
normalization_data=np.array(normalization_data)

print(normalization_data)

[[0.38 1.   0.   ... 0.79 0.01 0.04]
 [0.36 0.86 0.04 ... 0.78 0.01 0.05]
 [0.27 0.72 0.   ... 0.95 0.02 0.15]
 ...
 [0.   0.   0.   ... 1.   0.99 1.  ]
 [0.01 0.   0.   ... 0.02 0.41 0.19]
 [0.04 0.   0.36 ... 0.08 0.17 0.08]]


In [5]:
#四分位数离散化
labels=['D','C','B','A']
data['confirmedCount1']=pd.qcut(data['confirmedCount'],4,labels=labels)
data['confirmedCount1']

provinceName
法国         A
德国         A
韩国         A
意大利        A
英国         A
          ..
格陵兰        D
英属维尔京群岛    D
福克兰群岛      D
埃及         B
南非         A
Name: confirmedCount1, Length: 214, dtype: category
Categories (4, object): [D < C < B < A]